version: 2
updates:
  # 1. Gradle 설정
  - package-ecosystem: "gradle"
    directory: "/source/did-issuer-server"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Asia/Seoul"
    
    # 보안 업데이트만 받기 (일반 업데이트 차단)
    open-pull-requests-limit: 0
    
    reviewers:
      - "jhkim6557"
    assignees:
      - "jhkim6557"

  # 2. npm 설정
  - package-ecosystem: "npm"
    directory: "/source/did-issuer-admin/frontend"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Asia/Seoul"
      
    # 보안 업데이트만 받기 (일반 업데이트 차단)
    open-pull-requests-limit: 0

    reviewers:
      - "jhkim6557"
    assignees:
      - "jhkim6557"
