spring:
  application:
    name: Issuer
  profiles:
    active: sample
    group:
        dev:
          - database
          - wallet
          - logging
          - spring-docs
          - blockchain
        sample:
          - database-sample
          - wallet
          - logging
          - spring-docs
          - blockchain
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "shutdown"
  endpoint:
    health:
      show-details: "never"
    shutdown:
      enabled: true